version: '3'
services:
  users:
    container_name: users
    image: users:latest
    hostname: users
    build:
      context: ./backend/user-service
    env_file:
      - ./backend/user-service/.env
    ports:
      - "3001:3001"

  assignment:
    container_name: assignment
    image: assignment:latest
    hostname: assignment
    build:
      context: ./backend/assignment-service
    env_file:
      - ./backend/assignment-service/.env
    ports:
      - "8080:8080"

  grading:
    container_name: grading
    image: grading:latest
    hostname: grading
    build:
      context: ./backend/grading-service
    env_file:
      - ./backend/grading-service/.env
    ports:
      - "8088:8088"

  frontend:
    container_name: frontend
    image: frontend:latest
    hostname: frontend
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - users
      - grading
      - assignment